/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teca.view.cliente;


import java.util.Random;
import javax.swing.JOptionPane;
import teca.controller.clienteDAO;
import teca.model.Cliente;

/**
 *
 * @author 36127512021.2
 */
public class Cadastrar extends javax.swing.JFrame {
    clienteDAO CLDAO = new clienteDAO();
    Cliente CL = new Cliente();
    public Cadastrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cadastrarnome = new javax.swing.JTextField();
        cadastrarendereço = new javax.swing.JTextField();
        cadastrarcpf = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 440));
        setPreferredSize(new java.awt.Dimension(400, 440));
        setSize(new java.awt.Dimension(400, 440));
        getContentPane().setLayout(null);

        cadastrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrar);
        cadastrar.setBounds(100, 330, 100, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setText("Cadastrar - Cliente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 50, 200, 24);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 110, 40, 50);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Endereço:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 170, 70, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("CPF:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 210, 30, 50);

        cadastrarnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarnomeActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarnome);
        cadastrarnome.setBounds(130, 120, 180, 30);

        cadastrarendereço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarendereçoActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarendereço);
        cadastrarendereço.setBounds(130, 170, 180, 30);
        getContentPane().add(cadastrarcpf);
        cadastrarcpf.setBounds(130, 220, 180, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(170, 72, 0, 0);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(180, 82, 150, 0);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(160, 70, 0, 2);

        voltar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(220, 330, 80, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        Random RDM = new Random();
              
        if ( (cadastrarnome.getText().equals("")) || (cadastrarendereço.getText().equals("")) || (cadastrarcpf.getText().equals("")) ) {
            
            JOptionPane.showMessageDialog(null, "Boraaaaaaa!!!!\n"+
                                                "Preencha todos eles!!!!");
            cadastrarnome.setText("");
            cadastrarendereço.setText("");
            cadastrarcpf.setText("");                                             
            setVisible(true);
        }
         else{          
            //AQUI QUE COMEÇA
            CL.setNome(cadastrarnome.getText());
            CL.setEndereco(cadastrarendereço.getText());
            CL.setCpf(cadastrarcpf.getText());
            CL.setMatricula(RDM.nextInt(5555));           
            CLDAO.inserir(CL);
            
        }                                         
                                            
    }//GEN-LAST:event_cadastrarActionPerformed

    private void cadastrarendereçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarendereçoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarendereçoActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void cadastrarnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarnomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar;
    private javax.swing.JTextField cadastrarcpf;
    private javax.swing.JTextField cadastrarendereço;
    private javax.swing.JTextField cadastrarnome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
