/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teca.view.cliente;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.Random;
import javax.swing.JOptionPane;
import teca.controller.clienteDAO;
import teca.model.Cliente;

/**
 *
 * @author 36127512021.2
 */
public class Editar extends javax.swing.JFrame {
    clienteDAO CLDAO = new clienteDAO();
    Cliente CL = new Cliente();
    /**
     * Creates new form Editar
     */
    public Editar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        editarcpf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        editarendereco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        editarnome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        editar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        gerarNovaMatriculaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setText("Editar - cliente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 40, 220, 14);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("CPF:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 170, 34, 20);
        getContentPane().add(editarcpf);
        editarcpf.setBounds(110, 170, 190, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Endereço:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 130, 60, 20);

        editarendereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarenderecoActionPerformed(evt);
            }
        });
        getContentPane().add(editarendereco);
        editarendereco.setBounds(110, 130, 190, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Nome:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 90, 40, 20);

        editarnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarnomeActionPerformed(evt);
            }
        });
        getContentPane().add(editarnome);
        editarnome.setBounds(110, 90, 190, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Matrícula:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 210, 60, 20);

        editar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        getContentPane().add(editar);
        editar.setBounds(100, 260, 80, 23);

        voltar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(200, 260, 80, 23);

        gerarNovaMatriculaButton.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gerarNovaMatriculaButton.setForeground(new java.awt.Color(255, 0, 0));
        gerarNovaMatriculaButton.setText("Gerar nova matrícula");
        gerarNovaMatriculaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarNovaMatriculaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(gerarNovaMatriculaButton);
        gerarNovaMatriculaButton.setBounds(110, 210, 190, 23);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editarnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarnomeActionPerformed
    
    }//GEN-LAST:event_editarnomeActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
         if ( (editarnome.getText().equals("")) || (editarendereco.getText().equals("")) || (editarcpf.getText().equals("")) ) {
         
          JOptionPane.showMessageDialog(null, "NÃO PODE HAVER CAMPOS EM BRANCO!!!!\n"+
                                                "PREENCHA TODOS ELES !!!!");
            
           editarnome.setText("");
           editarendereco.setText("");
           editarcpf.setText("");
           
          
            setVisible(true);
        
        }else{
            CL.setNome(editarnome.getText());
            CL.setEndereco(editarendereco.getText());
            CL.setCpf(editarcpf.getText());
            CLDAO.editar(CL);
        }
    }//GEN-LAST:event_editarActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
         dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void editarenderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarenderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarenderecoActionPerformed

    private void gerarNovaMatriculaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarNovaMatriculaButtonActionPerformed
        // TODO add your handling code here:
        //NOTA: AO GERAR UMA NOVA MATRICULA, SE A MATRICULA ANTIGA ESTIVER ATRELADA AO EMPRESTIMO DE UM LIVRO NAO HAVERA COMO MUDAR! SO EXCLUINDO A MATRICULA DA TABELA EMPRESTIMO.
        if ( !((editarnome.getText().equals("")) || (editarendereco.getText().equals("")) || (editarcpf.getText().equals(""))) ) {
            CLDAO.gerarNovaMatricula(CL);
        } else {
            JOptionPane.showMessageDialog(null,"Não é possível gerar uma nova matrícula com os campos CPF, NOME E ENDEREÇO INVÁLIDOS!");
        }
    }//GEN-LAST:event_gerarNovaMatriculaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editar;
    private javax.swing.JTextField editarcpf;
    private javax.swing.JTextField editarendereco;
    private javax.swing.JTextField editarnome;
    private javax.swing.JButton gerarNovaMatriculaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
