/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teca.view.adm;


import javax.swing.JOptionPane;
import teca.view.adm.CadastrarADM;
import teca.view.adm.EditarADM;
import teca.view.adm.ExclusaoADM;


/**
 *
 * @author 36127512021.2
 */
public class TelaMenuADM extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdm
     */
    public TelaMenuADM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pesquisar12 = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        excluir1 = new javax.swing.JButton();
        cadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setText("Menu do ADM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 60, 132, 24);

        pesquisar12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pesquisar12.setText("Pesquisar");
        pesquisar12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisar12ActionPerformed(evt);
            }
        });
        getContentPane().add(pesquisar12);
        pesquisar12.setBounds(130, 130, 138, 30);

        editar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        getContentPane().add(editar);
        editar.setBounds(130, 180, 138, 30);

        excluir1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        excluir1.setText("Excluir");
        excluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluir1ActionPerformed(evt);
            }
        });
        getContentPane().add(excluir1);
        excluir1.setBounds(130, 230, 140, 30);

        cadastrar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrar);
        cadastrar.setBounds(130, 280, 138, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisar12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisar12ActionPerformed
          Pesquisar PE = new Pesquisar();
        
        JOptionPane.showMessageDialog(null, "Acesso Permitido  !!!!!\n"+
                                            "Você irá para a Tela de Pesquisa de Dados !!!");                                                    
        PE.setVisible(true);
    }//GEN-LAST:event_pesquisar12ActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        CadastrarADM TD = new CadastrarADM();
        
        JOptionPane.showMessageDialog(null, "Acesso Permitido  !!!!!\n"+
                                            "Você irá para a Tela de Cadastro de Dados de Empregados !!!");                                                    
      TD.setVisible(true);
    }//GEN-LAST:event_cadastrarActionPerformed
                                     
                                    

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        EditarADM ED = new EditarADM();
        
        JOptionPane.showMessageDialog(null, "Acesso Permitido  !!!!!\n"+
                                            "Você irá para a Tela de Edição !!!");                                                    
        ED.setVisible(true);
       
    }//GEN-LAST:event_editarActionPerformed

    private void excluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluir1ActionPerformed
             
      ExclusaoADM EXD = new ExclusaoADM();
        JOptionPane.showMessageDialog(null, "Acesso Permitido  !!!!!\n"+
                                            "Você irá para a Tela de Cadastro de Dados de Empregados !!!");   
        EXD.setVisible(true);  
    }//GEN-LAST:event_excluir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuADM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar;
    private javax.swing.JButton editar;
    private javax.swing.JButton excluir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pesquisar12;
    // End of variables declaration//GEN-END:variables
}
